import '../styles/globals.css';

import { AppType } from 'next/dist/shared/lib/utils';
import Head from 'next/head';

import Layout from '../components/Layout';

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <Layout>
      <Head>
        <title>Next Board</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{' '}
      <Component {...pageProps} />
    </Layout>
  );
};

export default MyApp;
